From http://www.jwz.org/xscreensaver/xscreensaver-5.16.tar.gz
-rw-r--r-- 1 zblaxell zblaxell 6921664 Jun 19 17:46 xscreensaver-5.16.tar.gz
71a9055fc50fef031b1e6937fd5a3e6569397de1  xscreensaver-5.16.tar.gz

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -650,6 +650,9 @@ HACKDIR
 NOGNOME
 GNOME22
 GNOME24
+GLFONT_OBJS
+GLFPS_OBJS
+JWZGLES_OBJS
 GLE_KLUDGE
 GLE_EXES
 GL_KLUDGE
@@ -679,6 +682,7 @@ DEFAULT_IMAGE_DIRECTORY
 DEFAULT_IMAGES_P
 NEW_LOGIN_COMMAND_P
 NEW_LOGIN_COMMAND
+COMMENT_PAM_CHECK_ACCOUNT
 HAVE_PAM_FAIL_DELAY
 INSTALL_PAM
 NEED_SETUID
@@ -822,6 +826,7 @@ enable_locking
 enable_root_passwd
 with_pam
 with_pam_service_name
+enable_pam_check_account_type
 with_kerberos
 with_shadow
 with_passwd_helper
@@ -830,6 +835,7 @@ with_gtk
 with_motif
 with_gl
 with_gle
+with_gles
 with_pixbuf
 with_xpm
 with_jpeg
@@ -1483,6 +1489,10 @@ Screen locking options:
 
   --enable-root-passwd	      Allow root passwd to unlock screen.
   --disable-root-passwd       Do not allow that.
+  --enable-pam-check-account-type
+                          Whether PAM should check the result of account
+                          modules when authenticating. Only do this if you
+                          have account configured properly on your system.
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -1527,6 +1537,7 @@ Graphics options:
   --with-gl               Build those demos which depend on OpenGL.
   --with-gle              Build those demos which depend on GLE
                           (the OpenGL "extrusion" library.)
+  --with-gles             Target OpenGL ES 1.x API instead of OpenGL 1.3.
   --with-pixbuf           Include support for the GDK-Pixbuf library in some
                           demos, which will make it possible for them to read
                           GIF, JPEG, and PNG files as well.
@@ -2041,6 +2052,15 @@ echo "command line was: $0 $@"
 #AH_TEMPLATE([HAVE_SGI_VC_EXTENSION],
 #	    [Define this if you have the SGI-VIDEO-CONTROL extension.  This
 #	    is standard on Irix systems, and not available elsewhere.])
+
+
+
+
+
+
+
+
+
 
 
 
@@ -13292,6 +13312,24 @@ else
 fi
 
 
+# Check whether --enable-pam-check-account-type was given.
+if test "${enable_pam_check_account_type+set}" = set; then
+  enableval=$enable_pam_check_account_type; enable_pam_check_account_type="$enableval"
+else
+  enable_pam_check_account_type=no
+fi
+
+if test "$enable_pam_check_account_type" = yes ; then
+  cat >>confdefs.h <<\_ACEOF
+#define PAM_CHECK_ACCOUNT_TYPE 1
+_ACEOF
+
+  true
+elif test "$enable_pam_check_account_type" != no ; then
+  echo "error: must be yes or no: --enable-pam-check-account-type=$enable_pam_check_account_type"
+  exit 1
+fi
+
 
    case "$with_pam" in
     yes) ;;
@@ -17371,7 +17409,7 @@ if test "${ac_cv_mesagl_version_string+set}" = set; then
   $as_echo_n "(cached) " >&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 17378 "configure"
+#line 17416 "configure"
 #include "confdefs.h"
 #include <GL/gl.h>
 #ifndef MESA_MAJOR_VERSION
@@ -18137,6 +18175,96 @@ elif test "$with_gle" != no; then
   echo "error: must be yes or no: --with-gle=$with_gle"
   exit 1
 
+fi
+
+
+###############################################################################
+#
+#       Handle --with-gles
+#
+###############################################################################
+
+with_gles_req=unspecified
+
+# Check whether --with-gles was given.
+if test "${with_gles+set}" = set; then
+  withval=$with_gles; with_gles="$withval"; with_gles_req="$withval"
+else
+  with_gles=no
+fi
+
+
+
+   case "$with_gles" in
+    yes) ;;
+    no)  ;;
+
+    /*)
+     { $as_echo "$as_me:$LINENO: checking for JWZGLES headers" >&5
+$as_echo_n "checking for JWZGLES headers... " >&6; }
+     d=$with_gles/include
+     if test -d $d; then
+       X_CFLAGS="-I$d $X_CFLAGS"
+       { $as_echo "$as_me:$LINENO: result: $d" >&5
+$as_echo "$d" >&6; }
+     else
+       { $as_echo "$as_me:$LINENO: result: not found ($d: no such directory)" >&5
+$as_echo "not found ($d: no such directory)" >&6; }
+     fi
+
+     { $as_echo "$as_me:$LINENO: checking for JWZGLES libs" >&5
+$as_echo_n "checking for JWZGLES libs... " >&6; }
+     d=$with_gles/lib
+     if test -d $d; then
+       X_LIBS="-L$d $X_LIBS"
+       { $as_echo "$as_me:$LINENO: result: $d" >&5
+$as_echo "$d" >&6; }
+     else
+       { $as_echo "$as_me:$LINENO: result: not found ($d: no such directory)" >&5
+$as_echo "not found ($d: no such directory)" >&6; }
+     fi
+
+     # replace the directory string with "yes".
+     with_gles_req="yes"
+     with_gles=$with_gles_req
+     ;;
+
+    *)
+     echo ""
+     echo "error: argument to --with-gles must be \"yes\", \"no\", or a directory."
+     echo "       If it is a directory, then \`DIR/include' will be added to"
+     echo "       the -I list, and \`DIR/lib' will be added to the -L list."
+     exit 1
+     ;;
+   esac
+
+
+if test "$with_gles" = yes; then
+  have_gles=yes
+  cat >>confdefs.h <<\_ACEOF
+#define HAVE_JWZGLES 1
+_ACEOF
+
+  JWZGLES_OBJS="jwzgles.o"
+  { $as_echo "$as_me:$LINENO: result: using OpenGL ES compatiblity shim" >&5
+$as_echo "using OpenGL ES compatiblity shim" >&6; }
+elif test "$with_gles" != no; then
+  echo "error: must be yes or no: --with-gles=$with_xpm"
+  exit 1
+fi
+
+# May want to phase out glBitmap even in a non-GLES world.
+#
+if test "$have_gles" = yes; then
+  GLFPS_OBJS="fps-gl.o glxfonts.o texfont.o"
+  GLFONT_OBJS=""
+else
+  cat >>confdefs.h <<\_ACEOF
+#define HAVE_GLBITMAP 1
+_ACEOF
+
+  GLFPS_OBJS="fps-gl.o glxfonts.o"
+  GLFONT_OBJS="texfont.o"
 fi
 
 
@@ -20951,6 +21079,11 @@ if test "$have_pam" = yes; then
   PASSWD_OBJS="$PASSWD_OBJS \$(PAM_OBJS)"
   INSTALL_PAM="install-pam"
 fi
+if test "$enable_pam_check_account_type" = yes; then
+  COMMENT_PAM_CHECK_ACCOUNT=""
+else
+  COMMENT_PAM_CHECK_ACCOUNT="#"
+fi
 if test "$have_passwd_helper" = yes; then
   PASSWD_SRCS="$PASSWD_SRCS \$(PWHELPER_SRCS)"
   PASSWD_OBJS="$PASSWD_OBJS \$(PWHELPER_OBJS)"
@@ -21142,6 +21275,10 @@ INCLUDES=`echo "$INCLUDES" | sed 's@ -I${prefix}/include@@g;'`
 
 
 
+
+
+
+
 APPDEFAULTS=$ac_x_app_defaults
 
 
@@ -21150,7 +21287,7 @@ APPDEFAULTS=$ac_x_app_defaults
 
 
 
-ac_config_files="$ac_config_files Makefile utils/Makefile driver/Makefile hacks/Makefile hacks/glx/Makefile po/Makefile.in driver/XScreenSaver.ad"
+ac_config_files="$ac_config_files Makefile utils/Makefile driver/Makefile driver/xscreensaver.pam hacks/Makefile hacks/glx/Makefile po/Makefile.in driver/XScreenSaver.ad"
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -21769,6 +21906,7 @@ do
     "Makefile") CONFIG_FILES="$CONFIG_FILES Makefile" ;;
     "utils/Makefile") CONFIG_FILES="$CONFIG_FILES utils/Makefile" ;;
     "driver/Makefile") CONFIG_FILES="$CONFIG_FILES driver/Makefile" ;;
+    "driver/xscreensaver.pam") CONFIG_FILES="$CONFIG_FILES driver/xscreensaver.pam" ;;
     "hacks/Makefile") CONFIG_FILES="$CONFIG_FILES hacks/Makefile" ;;
     "hacks/glx/Makefile") CONFIG_FILES="$CONFIG_FILES hacks/glx/Makefile" ;;
     "po/Makefile.in") CONFIG_FILES="$CONFIG_FILES po/Makefile.in" ;;
