From https://www.jwz.org/xscreensaver/xscreensaver-6.11.tar.gz
-rw-rw-r-- 1 zblaxell zblaxell 25158311 Jul  1 21:54 xscreensaver-6.11.tar.gz
3b44aa3829dee9508fa0def1c7e82a4d03dc30e7  xscreensaver-6.11.tar.gz

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -687,6 +687,11 @@ SETCAP_HACKS
 SETUID_HACKS
 SETUID_AUTH
 PROG_SETCAP
+WAYLAND_IDLE_OBJS
+WAYLAND_GEN
+WAYLAND_DATADIR
+WAYLAND_LIBS
+WAYLAND_CFLAGS
 LIBCAP_LIBS
 LIBCAP_CFLAGS
 PASSWD_LIBS
@@ -847,8 +852,8 @@ enable_rpath
 with_libiconv_prefix
 with_libintl_prefix
 with_app_defaults
+enable_dependency_tracking
 with_hackdir
-enable_subdir
 with_configdir
 with_fontdir
 with_dpms_ext
@@ -867,6 +872,7 @@ with_proc_interrupts
 with_proc_oom
 with_systemd
 with_elogind
+with_wayland
 enable_locking
 enable_root_passwd
 with_pam
@@ -1536,16 +1542,18 @@ Server Extension Options:
   --with-systemd          Support systemd requests to lock on suspend, and to
                           allow video players to inhibit the screen saver.
   --with-elogind          Use elogind instead of systemd.
+  --with-wayland          Use native Wayland when available.
 
 Screen Locking Options:
 
   --disable-locking       Do not allow locking of the display at all.
   --with-pam              Use Pluggable Authentication Modules.
   --with-pam-service-name Set the name of the xscreensaver PAM service.
-  --enable-pam-account    Whether PAM should check the result of account
-	    		  modules when authenticating.  Only do this if you
-	    		  have "account" modules configured on your system.
-  --enable-root-passwd	  Allow the root password to unlock, if not using PAM.
+  --enable-pam-check-account-type
+                          Whether PAM should check the result of account
+                          modules when authenticating.  Only do this if you
+                          have "account" modules configured on your system.
+  --enable-root-passwd    Allow the root password to unlock, if not using PAM.
   --with-kerberos         Include support for Kerberos authentication.
   --with-shadow           Include support for shadow password authentication.
 
@@ -10149,6 +10157,13 @@ fi
 printf "%s\n" "$ac_cv_x_app_defaults" >&6; }
     eval ac_x_app_defaults="$ac_cv_x_app_defaults"
 
+# Ignore --disable-dependency-tracking, which RHEL8 rpmbuild adds by default.
+# Check whether --enable-dependency-tracking was given.
+if test ${enable_dependency_tracking+y}
+then :
+  enableval=$enable_dependency_tracking;
+fi
+
 ###############################################################################
 #
 #       Handle the --with-hackdir option
@@ -10180,23 +10195,6 @@ HACKDIR=`echo "${HACKDIR}" | sed 's@/$@@;s@//*@/@g'`
 
 # Expand HACKDIR as HACKDIR_FULL
 HACKDIR_FULL=`eval eval eval eval eval eval eval eval eval echo $HACKDIR`
-
-# This option used to be called --enable-subdir; make sure that is no longer
-# used, since configure brain-damagedly ignores unknown --enable options.
-
-obsolete_enable=
-# Check whether --enable-subdir was given.
-if test ${enable_subdir+y}
-then :
-  enableval=$enable_subdir; obsolete_enable=yes
-fi
-
-if test -n "$obsolete_enable"; then
-  echo "error: the --enable-subdir option has been replaced with"
-  echo "       the new --with-hackdir option; see \`configure --help'"
-  echo "       for more information."
-  exit 1
-fi
 
 ###############################################################################
 #
@@ -13415,6 +13413,230 @@ if test "$have_elogind" = yes; then
   EXES_SYSTEMD='$(EXES_SYSTEMD)'
   SYSTEMD_LIBS="$ac_elogind_config_libs"
   printf "%s\n" "#define HAVE_LIBELOGIND 1" >>confdefs.h
+
+fi
+
+###############################################################################
+#
+#       Check for Wayland
+#
+###############################################################################
+
+have_wayland=no
+with_wayland_req=unspecified
+
+# Check whether --with-wayland was given.
+if test ${with_wayland+y}
+then :
+  withval=$with_wayland; with_wayland="$withval"; with_wayland_req="$withval"
+else case e in #(
+  e) with_wayland=yes ;;
+esac
+fi
+
+   case "$with_wayland" in
+    yes) ;;
+    no)  ;;
+
+    /*)
+     { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for Wayland headers" >&5
+printf %s "checking for Wayland headers... " >&6; }
+     d=$with_wayland/include
+     if test -d $d; then
+       X_CFLAGS="-I$d $X_CFLAGS"
+       { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $d" >&5
+printf "%s\n" "$d" >&6; }
+     else
+       { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: not found ($d: no such directory)" >&5
+printf "%s\n" "not found ($d: no such directory)" >&6; }
+     fi
+
+     { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for Wayland libs" >&5
+printf %s "checking for Wayland libs... " >&6; }
+     d=$with_wayland/lib
+     if test -d $d; then
+       X_LIBS="-L$d $X_LIBS"
+       { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $d" >&5
+printf "%s\n" "$d" >&6; }
+     else
+       { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: not found ($d: no such directory)" >&5
+printf "%s\n" "not found ($d: no such directory)" >&6; }
+     fi
+
+     # replace the directory string with "yes".
+     with_wayland_req="yes"
+     with_wayland=$with_wayland_req
+     ;;
+
+    *)
+     echo ""
+     echo "error: argument to --with-wayland must be \"yes\", \"no\", or a directory."
+     echo "       If it is a directory, then \`DIR/include' will be added to"
+     echo "       the -I list, and \`DIR/lib' will be added to the -L list."
+     exit 1
+     ;;
+   esac
+
+if test "$with_wayland" != yes -a "$with_wayland" != no ; then
+  echo "error: must be yes or no: --with-wayland=$with_wayland"
+  exit 1
+fi
+
+if test "$with_wayland" = yes; then
+  have_wayland=no
+
+  pkgs=''
+  ok="yes"
+  pkg_check_version       wayland-server  1.0
+  pkg_check_version       wayland-client  1.0
+  pkg_check_version       wayland-scanner 1.0
+  ac_wayland_version_string="$vers"
+  have_wayland="$ok"
+  wayland_pkgs="$pkgs"
+
+  if test "$have_wayland" = yes; then
+    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for Wayland includes" >&5
+printf %s "checking for Wayland includes... " >&6; }
+if test ${ac_cv_wayland_config_cflags+y}
+then :
+  printf %s "(cached) " >&6
+else case e in #(
+  e) ac_cv_wayland_config_cflags=`$pkg_config --cflags $pkgs` ;;
+esac
+fi
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $ac_cv_wayland_config_cflags" >&5
+printf "%s\n" "$ac_cv_wayland_config_cflags" >&6; }
+    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for Wayland libs" >&5
+printf %s "checking for Wayland libs... " >&6; }
+if test ${ac_cv_wayland_config_libs+y}
+then :
+  printf %s "(cached) " >&6
+else case e in #(
+  e) ac_cv_wayland_config_libs=`$pkg_config --libs $pkgs` ;;
+esac
+fi
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $ac_cv_wayland_config_libs" >&5
+printf "%s\n" "$ac_cv_wayland_config_libs" >&6; }
+  fi
+
+  ac_wayland_config_cflags=$ac_cv_wayland_config_cflags
+  ac_wayland_config_libs=$ac_cv_wayland_config_libs
+
+  WAYLAND_DATADIR=""
+  WAYLAND_GEN=""
+  WAYLAND_IDLE_OBJS=""
+  if test "$have_wayland" = yes; then
+    WAYLAND_DATADIR=`$pkg_config --variable=prefix wayland-client`
+    WAYLAND_DATADIR="$WAYLAND_DATADIR/share"
+    WAYLAND_GEN='$(WAYLAND_GEN_HDRS) $(WAYLAND_GEN_SRCS)'
+    WAYLAND_IDLE_OBJS='$(WAYLAND_IDLE_OBJS_1)'
+  fi
+
+  if test "$have_wayland" = yes; then
+    INCLUDES="$INCLUDES $ac_wayland_config_cflags"
+    WAYLAND_LIBS="$WAYLAND_LIBS $ac_wayland_config_libs"
+    printf "%s\n" "#define HAVE_WAYLAND 1" >>confdefs.h
+
+  fi
+fi
+
+# Check for the various Gnome help and URL loading programs.
+#
+WITH_BROWSER=gnome-open
+if test "$have_wayland" = yes; then
+  for ac_prog in gnome-open
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
+printf %s "checking for $ac_word... " >&6; }
+if test ${ac_cv_prog_gnome_open_program+y}
+then :
+  printf %s "(cached) " >&6
+else case e in #(
+  e) if test -n "$gnome_open_program"; then
+  ac_cv_prog_gnome_open_program="$gnome_open_program" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  case $as_dir in #(((
+    '') as_dir=./ ;;
+    */) ;;
+    *) as_dir=$as_dir/ ;;
+  esac
+    for ac_exec_ext in '' $ac_executable_extensions; do
+  if as_fn_executable_p "$as_dir$ac_word$ac_exec_ext"; then
+    ac_cv_prog_gnome_open_program="$ac_prog"
+    printf "%s\n" "$as_me:${as_lineno-$LINENO}: found $as_dir$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+  done
+IFS=$as_save_IFS
+
+fi ;;
+esac
+fi
+gnome_open_program=$ac_cv_prog_gnome_open_program
+if test -n "$gnome_open_program"; then
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $gnome_open_program" >&5
+printf "%s\n" "$gnome_open_program" >&6; }
+else
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
+printf "%s\n" "no" >&6; }
+fi
+
+  test -n "$gnome_open_program" && break
+done
+
+  for ac_prog in gnome-url-show
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
+printf %s "checking for $ac_word... " >&6; }
+if test ${ac_cv_prog_gnome_url_show_program+y}
+then :
+  printf %s "(cached) " >&6
+else case e in #(
+  e) if test -n "$gnome_url_show_program"; then
+  ac_cv_prog_gnome_url_show_program="$gnome_url_show_program" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  case $as_dir in #(((
+    '') as_dir=./ ;;
+    */) ;;
+    *) as_dir=$as_dir/ ;;
+  esac
+    for ac_exec_ext in '' $ac_executable_extensions; do
+  if as_fn_executable_p "$as_dir$ac_word$ac_exec_ext"; then
+    ac_cv_prog_gnome_url_show_program="$ac_prog"
+    printf "%s\n" "$as_me:${as_lineno-$LINENO}: found $as_dir$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+  done
+IFS=$as_save_IFS
+
+fi ;;
+esac
+fi
+gnome_url_show_program=$ac_cv_prog_gnome_url_show_program
+if test -n "$gnome_url_show_program"; then
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $gnome_url_show_program" >&5
+printf "%s\n" "$gnome_url_show_program" >&6; }
+else
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
+printf "%s\n" "no" >&6; }
+fi
+
+  test -n "$gnome_url_show_program" && break
+done
 
 fi
 
@@ -21166,14 +21388,6 @@ else
 fi
 PASSWD_SRCS="$PASSWD_SRCS \$(PWENT_SRCS)"
 PASSWD_OBJS="$PASSWD_OBJS \$(PWENT_OBJS)"
-
-if test "$enable_locking" = yes; then
-  LOCK_SRCS='$(LOCK_SRCS_1) $(PASSWD_SRCS)'
-  LOCK_OBJS='$(LOCK_OBJS_1) $(PASSWD_OBJS)'
-else
-  LOCK_SRCS='$(NOLOCK_SRCS_1)'
-  LOCK_OBJS='$(NOLOCK_OBJS_1)'
-fi
 
 if test "$ac_macosx" = yes; then
   EXES_OSX='$(EXES_OSX)'
