From http://www.jwz.org/xscreensaver/xscreensaver-5.16.tar.gz
-rw-r--r-- 1 zblaxell zblaxell 6921664 Jun 19 17:46 xscreensaver-5.16.tar.gz
71a9055fc50fef031b1e6937fd5a3e6569397de1  xscreensaver-5.16.tar.gz

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -190,6 +190,11 @@ AH_TEMPLATE([HAVE_GLE],
 
 AH_TEMPLATE([HAVE_GLE3],[Define this if you have the -lgle from GLE version 3])
 
+AH_TEMPLATE([HAVE_JWZGLES],[Define this to target the OpenGL ES 1.x API
+	    instead of OpenGL 1.3.])
+
+AH_TEMPLATE([HAVE_GLBITMAP],[Define this if glBitmap exists.])
+
 AH_TEMPLATE([HAVE_XSHM_EXTENSION],
 	    [Define this if you have the X Shared Memory Extension.])
 
@@ -244,6 +249,11 @@ AH_TEMPLATE([PAM_SERVICE_NAME],
 AH_TEMPLATE([HAVE_PAM_FAIL_DELAY],
 	    [Define this if you have pam_fail_delay function.
 	    see driver/passwd-pam.c.])
+
+AH_TEMPLATE([PAM_CHECK_ACCOUNT_TYPE],
+            [Whether PAM should check the result of account modules
+	    when authenticating.  Only do this if you have account
+	    configured properly on your system.])
 
 AH_TEMPLATE([PAM_STRERROR_TWO_ARGS],
 	    [Define if you have PAM and pam_strerror() requires two
@@ -1925,6 +1935,20 @@ AC_ARG_WITH([pam_service_name],
 	    		   xscreensaver will authenticate as.]),
 	    [pam_service_name="$withval"],[pam_service_name="xscreensaver"])
 
+AC_ARG_ENABLE(pam-check-account-type,
+  [AC_HELP_STRING([--enable-pam-check-account-type],
+	    		   [Whether PAM should check the result of account
+	    		   modules when authenticating.  Only do this if you
+	    		   have account configured properly on your system.])],
+  [enable_pam_check_account_type="$enableval"],[enable_pam_check_account_type=no])
+if test "$enable_pam_check_account_type" = yes ; then
+  AC_DEFINE(PAM_CHECK_ACCOUNT_TYPE)
+  true
+elif test "$enable_pam_check_account_type" != no ; then
+  echo "error: must be yes or no: --enable-pam-check-account-type=$enable_pam_check_account_type"
+  exit 1
+fi
+
 HANDLE_X_PATH_ARG(with_pam, --with-pam, PAM)
 
 if test "$enable_locking" = yes -a "$with_pam" = yes; then
@@ -3069,6 +3093,41 @@ fi
 
 ###############################################################################
 #
+#       Handle --with-gles
+#
+###############################################################################
+
+with_gles_req=unspecified
+AC_ARG_WITH(gles,
+[  --with-gles             Target OpenGL ES 1.x API instead of OpenGL 1.3.],
+  [with_gles="$withval"; with_gles_req="$withval"],[with_gles=no])
+
+HANDLE_X_PATH_ARG(with_gles, --with-gles, JWZGLES)
+
+if test "$with_gles" = yes; then
+  have_gles=yes
+  AC_DEFINE(HAVE_JWZGLES)
+  JWZGLES_OBJS="jwzgles.o"
+  AC_MSG_RESULT(using OpenGL ES compatiblity shim)
+elif test "$with_gles" != no; then
+  echo "error: must be yes or no: --with-gles=$with_xpm"
+  exit 1
+fi
+
+# May want to phase out glBitmap even in a non-GLES world.
+#
+if test "$have_gles" = yes; then
+  GLFPS_OBJS="fps-gl.o glxfonts.o texfont.o"
+  GLFONT_OBJS=""
+else
+  AC_DEFINE(HAVE_GLBITMAP)
+  GLFPS_OBJS="fps-gl.o glxfonts.o"
+  GLFONT_OBJS="texfont.o"
+fi
+
+
+###############################################################################
+#
 #       Check for -lgdk_pixbuf.
 #       These tests are for gdk_pixbuf usage of the hacks, 
 #       not xscreensaver-demo (thus we have to test again to get
@@ -3652,6 +3711,11 @@ if test "$have_pam" = yes; then
   PASSWD_OBJS="$PASSWD_OBJS \$(PAM_OBJS)"
   INSTALL_PAM="install-pam"
 fi
+if test "$enable_pam_check_account_type" = yes; then
+  COMMENT_PAM_CHECK_ACCOUNT=""
+else
+  COMMENT_PAM_CHECK_ACCOUNT="#"
+fi
 if test "$have_passwd_helper" = yes; then
   PASSWD_SRCS="$PASSWD_SRCS \$(PWHELPER_SRCS)"
   PASSWD_OBJS="$PASSWD_OBJS \$(PWHELPER_OBJS)"
@@ -3800,6 +3864,7 @@ AC_SUBST(INSTALL_DIRS)
 AC_SUBST(NEED_SETUID)
 AC_SUBST(INSTALL_PAM)
 AC_SUBST(HAVE_PAM_FAIL_DELAY)
+AC_SUBST(COMMENT_PAM_CHECK_ACCOUNT)
 AC_SUBST(NEW_LOGIN_COMMAND)
 AC_SUBST(NEW_LOGIN_COMMAND_P)
 AC_SUBST(DEFAULT_IMAGES_P)
@@ -3831,6 +3896,9 @@ AC_SUBST(GL_MEN)
 AC_SUBST(GL_KLUDGE)
 AC_SUBST(GLE_EXES)
 AC_SUBST(GLE_KLUDGE)
+AC_SUBST(JWZGLES_OBJS)
+AC_SUBST(GLFPS_OBJS)
+AC_SUBST(GLFONT_OBJS)
 AC_SUBST(GNOME24)
 AC_SUBST(GNOME22)
 AC_SUBST(NOGNOME)
@@ -3852,6 +3920,7 @@ AC_SUBST(PERL)
 AC_OUTPUT(Makefile
           utils/Makefile
           driver/Makefile
+          driver/xscreensaver.pam
           hacks/Makefile
           hacks/glx/Makefile
           po/Makefile.in
