From http://www.jwz.org/xscreensaver/xscreensaver-5.35.tar.gz
-rw-r--r-- 1 zblaxell zblaxell 10502468 May 24 14:06 xscreensaver-5.35.tar.gz
2918e9db7a6d24189c5bcc401cec2d3adbee644b  xscreensaver-5.35.tar.gz

diff --git a/OSX/Makefile b/OSX/Makefile
--- a/OSX/Makefile
+++ b/OSX/Makefile
@@ -1,21 +1,23 @@
-# XScreenSaver for MacOS X, Copyright (c) 2006-2014 by Jamie Zawinski.
+# XScreenSaver for MacOS X, Copyright (c) 2006-2015 by Jamie Zawinski.
 
-# We have to use Xcode 5.0.2 in order to build savers that will run on
-# MacOS 10.6 and 10.7, because that's the latest version of Xcode that
-# ships with a version of clang that implements "-fobjc-gc".
+XCODE_APP = /Applications/Xcode.app
+
+# To build savers that will run on MacOS 10.6 and 10.7, Xcode 5.0.2 must
+# be used (as that's the latest version of Xcode that ships with a version
+# of clang that implements "-fobjc-gc").  However, Xcode 5.0.2 will not
+# launch on MacOS 10.11 or later.
 #
-XCODE_APP = /Applications/Xcode-5.0.2.app
+# XCODE_APP = /Applications/Xcode-5.0.2.app
 
 TARGETS    = All Savers
-ARCH       = -arch i386 -arch x86_64
+ARCH       = -arch i386 -arch x86_64 ONLY_ACTIVE_ARCH=NO
 CERT       = 'Jamie Zawinski'
 CERT       = 'iPhone Developer: Jamie Zawinski (Y5M82TL69N)'
 PKGID	   = org.jwz.xscreensaver
-THUMBDIR   = $(HOME)/www/xscreensaver/screenshots/
+THUMBDIR   = build/screenshots
 XCODEBUILD = $(XCODE_APP)/Contents/Developer/usr/bin/xcodebuild
 SETFILE    = $(XCODE_APP)/Contents/Developer/Tools/SetFile
-SETICON    = /usr/local/bin/seticon
-# seticon is from osxutils1.7.pkg
+SETICON    = ./seticon.pl
 
 default: release
 all: debug release
@@ -40,11 +42,62 @@ release:: distdepend
 	$(XCODEBUILD) $(ARCH) -target "$(TARGETS)" -configuration Release build
 
 release:: check_versions
-release:: update_thumbs
 release:: sign
 
 Sparkle.framework:
 	unzip ../archive/Sparkle.framework-2013-12-04.zip
+
+# Download and resize images from jwz.org.
+# This saves us having to include 4MB of images in the tar file
+# that will only be used by a vast minority of people building
+# from source.
+# update-info-plist.pl runs this as needed.
+# Might be better to do this with curl, since that is installed by default.
+
+URL = https://www.jwz.org/xscreensaver/screenshots/
+WGET = wget -q -U xscreensaver-build-osx
+CVT  = -thumbnail '200x150^' -gravity center -extent 200x150 \
+     \( +clone  -alpha extract \
+        -draw 'fill black polygon 0,0 0,6 6,0 fill white circle 6,6 6,0' \
+        \( +clone -flip \) -compose Multiply -composite \
+        \( +clone -flop \) -compose Multiply -composite \
+     \) -alpha off -compose CopyOpacity -composite \
+    -colorspace sRGB \
+    -strip \
+    -quality 95 \
+    +dither -colors 128
+
+$(THUMBDIR)/%.png:
+	@\
+	FILE1=`echo "$@" | sed 's!^.*/\([^/]*\)\.png$$!\1.jpg!'` ;	\
+	FILE2="$@" ;							\
+	TMP="$$FILE2".tmp ;						\
+	URL="$(URL)$$FILE1" ;						\
+	URL2="$(URL)retired/$$FILE1" ;					\
+	if [ ! -d $(THUMBDIR) ]; then mkdir -p $(THUMBDIR) ; fi ;	\
+	rm -f "$$FILE2" "$$TMP" ;					\
+	set +e ;							\
+	echo "downloading $$URL..." ;					\
+	$(WGET) -O"$$TMP" "$$URL" ;					\
+	if [ ! -s "$$TMP" ]; then					\
+	  echo "downloading $$URL2..." ;				\
+	  $(WGET) -O"$$TMP" "$$URL2" ;					\
+	fi ;								\
+	if [ ! -s "$$TMP" ]; then					\
+	  rm -f "$$TMP" ;						\
+	  echo "failed: $$URL" ;					\
+	  exit 1 ;							\
+	fi ;								\
+	rm -f "$$FILE2" ;						\
+	convert jpg:- $(CVT) "$$FILE2" < "$$TMP" ;			\
+	if [ ! -s "$$FILE2" ]; then					\
+	  echo "$$FILE2 failed" >&2 ;					\
+	  rm -f "$$FILE2" "$$TMP" ;					\
+	  exit 1 ;							\
+	else								\
+	  rm -f "$$TMP" ;						\
+	fi
+
 
 sign:
 	@for f in build/Release/*.app/Contents/*/*.saver \
@@ -129,10 +182,6 @@ check_coretext:
   done ;								\
   if [ "$$RESULT" = 0 ]; then echo "CoreText linked correctly" ; fi ;	\
   exit $$RESULT
-
-
-update_thumbs::
-	./update-thumbnail.pl $(THUMBDIR) build/Release/*.saver
 
 
 # Arrrrgh
@@ -235,7 +284,8 @@ build/Release/installer.pkg: installer.rtf installer.xml installer.sh installer.
 
 # -format UDBZ saves 4% (~1.2 MB) over UDZO.
 dmg:: distdepend
-dmg:: check_versions check_gc check_coretext
+dmg:: check_versions check_coretext
+#dmg:: check_gc
 dmg:: build/Release/installer.pkg
 dmg::
 	@								      \
@@ -291,7 +341,7 @@ dmg::
   cp -p bindist.rtf "$$STAGE/Read Me.rtf" ;				      \
   cp -p build/Release/installer.pkg "$$PKG" ;				      \
   cp -p bindist-DS_Store "$$STAGE/.DS_Store" ;				      \
-  cp -p bindist.webloc "$$STAGE/Get the iPhone:iPad Version.webloc" ;	      \
+  cp -p bindist.webloc "$$STAGE/" ;					      \
   cp -p XScreenSaverDMG.icns "$$STAGE/.VolumeIcon.icns" ;		      \
   ${SETFILE} -a C "$$STAGE" ;						      \
   ${SETFILE} -a E "$$STAGE"/*.{rtf,pkg,webloc} ;			      \
@@ -300,6 +350,7 @@ dmg::
   $(SETICON) -d XScreenSaverFolder.icns "$$DST" ;			      \
   $(SETICON) -d XScreenSaverWebloc.icns "$$STAGE"/*.webloc ;		      \
   $(SETICON) -d XScreenSaverPkg.icns "$$STAGE"/*.pkg ;			      \
+  mv "$$STAGE/bindist.webloc" "$$STAGE/Get the iPhone:iPad Version.webloc" ;  \
   hdiutil makehybrid -quiet -ov -hfs -hfs-volume-name "$$VOLNAME"	      \
     -hfs-openfolder "$$STAGE" "$$STAGE" -o "$$TMPDMG" ;			      \
   rm -rf "$$STAGE" ;							      \
diff --git a/android/Makefile b/android/Makefile
--- a/android/Makefile
+++ b/android/Makefile
@@ -1,44 +1,382 @@
 # XScreenSaver for Android
 
+export TERM=dumb
+GRADLE = cd project ; ./gradlew
 
-TARGET		= project
+default:: debug
+all:: release
 
-default: apk
-
-clean:: gradle_clean
-
-distclean::
+clean::
+	$(GRADLE) clean
 
 distdepend::
 
-all:
-	cd project ; ./gradlew assembleDebug
+# Set this to the set of platforms you want to compile for in debug mode.
+# E.g., if you are running an x86 emulator, there's no point in compiling
+# for a dozen other platforms.  Release builds override this to "all".
+#
+export APP_ABI = all
+
 
 # TODO:
 # check_versions:
-# update_thumbs:
+
+
+# These hacks have interdependencies with others, so we can't build without
+# including them or there are link errors:
+#
+ANDROID_BASE_HACKS=		\
+	apple2			\
+	bubble3d		\
+	pacman			\
+	polyhedra		\
+	sonar			\
+	sproingies		\
+
+# These are the ones that currently work, at least to some degree:
+#
+export ANDROID_HACKS=		\
+	$(ANDROID_BASE_HACKS)	\
+	abstractile		\
+	anemone			\
+	anemotaxis		\
+	apollonian		\
+	attraction		\
+	atunnel			\
+	blaster			\
+	blinkbox		\
+	blocktube		\
+	boing			\
+	bouncingcow		\
+	boxed			\
+	boxfit			\
+	braid			\
+	bsod			\
+	cage			\
+	ccurve			\
+	cloudlife		\
+	companioncube		\
+	compass			\
+	coral			\
+	crystal			\
+	cubestorm		\
+	cwaves			\
+	cynosure		\
+	dangerball		\
+	decayscreen		\
+	deco			\
+	demon			\
+	discrete		\
+	distort			\
+	dnalogo			\
+	drift			\
+	energystream		\
+	engine			\
+	epicycle		\
+	eruption		\
+	euler2d			\
+	fadeplot		\
+	fiberlamp		\
+	fireworkx		\
+	flame			\
+	flipflop		\
+	flow			\
+	fluidballs		\
+	flyingtoasters		\
+	fuzzyflakes		\
+	galaxy			\
+	gears			\
+	geodesic		\
+	geodesicgears		\
+	glcells			\
+	glknots			\
+	glmatrix		\
+	glschool		\
+	glsnake			\
+	gltext			\
+	grav			\
+	greynetic		\
+	helix			\
+	hexadrop		\
+	hilbert			\
+	hopalong		\
+	hypnowheel		\
+	ifs			\
+	imsmap			\
+	interference		\
+	intermomentary		\
+	julia			\
+	kaleidescope		\
+	kaleidocycle		\
+	klein			\
+	kumppa			\
+	lament			\
+	lavalite		\
+	loop			\
+	m6502			\
+	maze			\
+	memscroller		\
+	menger			\
+	metaballs		\
+	moebiusgears		\
+	moire			\
+	morph3d			\
+	nerverot		\
+	noof			\
+	penetrate		\
+	penrose			\
+	petri			\
+	piecewise		\
+	pinion			\
+	polytopes		\
+	pong			\
+	popsquares		\
+	providence		\
+	pyro			\
+	quasicrystal		\
+	raverhoop		\
+	rd-bomb			\
+	ripples			\
+	romanboy		\
+	rorschach		\
+	rotzoomer		\
+	rubik			\
+	rubikblocks		\
+	sballs			\
+	shadebobs		\
+	sierpinski		\
+	sierpinski3d		\
+	slidescreen		\
+	squiral			\
+	stairs			\
+	starfish		\
+	stonerview		\
+	strange			\
+	substrate		\
+	superquadrics		\
+	swirl			\
+	tangram			\
+	thornbird		\
+	timetunnel		\
+	topblock		\
+	triangle		\
+	tronbit			\
+	twang			\
+	unknownpleasures	\
+	vermiculate		\
+	voronoi			\
+	wander			\
+	whirlwindwarp		\
+	winduprobot		\
+	wormhole		\
+	xflame			\
+	xlyap			\
+	xspirograph		\
+
+
+# These don't work well enough to turn on by default:
+#
+ANDROID_TODO=			\
+	antinspect		\
+	antmaze			\
+	antspotlight		\
+	atlantis		\
+	barcode			\
+	binaryring		\
+	blitspin		\
+	bouboule		\
+	bumps			\
+	carousel		\
+	celtic			\
+	circuit			\
+	cityflow		\
+	crackberg		\
+	cube21			\
+	cubenetic		\
+	cubicgrid		\
+	deluxe			\
+	dymaxionmap		\
+	endgame			\
+	flipscreen3d		\
+	fliptext		\
+	fontglide		\
+	gflux			\
+	glblur			\
+	gleidescope		\
+	glhanoi			\
+	glplanet		\
+	glslideshow		\
+	goop			\
+	halftone		\
+	halo			\
+	hypertorus		\
+	interaggregate		\
+	jigglypuff		\
+	jigsaw			\
+	juggler3d		\
+	mirrorblob		\
+	moebius			\
+	moire2			\
+	molecule		\
+	mountain		\
+	munch			\
+	noseguy			\
+	pedal			\
+	phosphor		\
+	photopile		\
+	pipes			\
+	polyominoes		\
+	projectiveplane		\
+	pulsar			\
+	qix			\
+	queens			\
+	rocks			\
+	skytentacles		\
+	slip			\
+	speedmine		\
+	spheremonics		\
+	splitflap		\
+	spotlight		\
+	starwars		\
+	surfaces		\
+	tessellimage		\
+	testx11			\
+	truchet			\
+	unicrud			\
+	xanalogtv		\
+	xjack			\
+	xmatrix			\
+	xrayswarm		\
+	zoom			\
+
+
+# Download and resize images from jwz.org.
+# This saves us having to include 4MB of images in the tar file
+# that will only be used by a vast minority of people building
+# from source.
+# Android actually wants these to be 160x160 but our source is 200x150.
+
+URL = https://www.jwz.org/xscreensaver/screenshots/
+WGET = wget -q -U xscreensaver-build-android
+CVT  = -thumbnail '150x150^' -gravity center -extent 150x150 \
+     \( +clone  -alpha extract \
+        -draw 'fill black polygon 0,0 0,15 15,0 fill white circle 15,15 15,0' \
+        \( +clone -flip \) -compose Multiply -composite \
+        \( +clone -flop \) -compose Multiply -composite \
+     \) -alpha off -compose CopyOpacity -composite \
+    -colorspace sRGB \
+    -strip \
+    -quality 95 \
+    +dither -colors 128
+
+
+project/xscreensaver/res/drawable/%.png:
+	@\
+	FILE1=`echo "$@" | sed 's!^.*/\([^/]*\)\.png$$!\1.jpg!'` ;	\
+	FILE2="$@" ;							\
+	FILE1=`echo "$$FILE1" | sed s/rdbomb/rd-bomb/` ;		\
+	FILE2=`echo "$$FILE2" | sed s/rd-bomb/rdbomb/` ;		\
+	URL="$(URL)$$FILE1" ;						\
+	echo "converting $$URL..." ;					\
+	rm -f "$$FILE2" ;						\
+	$(WGET) -O- "$$URL" |						\
+	convert jpg:- $(CVT) "$$FILE2" ;				\
+	if [ ! -s "$$FILE2" ]; then					\
+	  echo "$$FILE2 failed" >&2 ;					\
+	  exit 1 ;							\
+	fi
+
+thumbs::
+	@for f in $(ANDROID_HACKS) $(ANDROID_TODO) ; do			\
+	  $(MAKE) project/xscreensaver/res/drawable/$$f.png ;		\
+	done
+
+clean_thumbs::
+	@\
+	for f in $(ANDROID_HACKS) $(ANDROID_TODO) ; do			\
+	  rm -f project/xscreensaver/res/drawable/$$f.png ;		\
+	done
+distclean:: clean_thumbs
+
+
+EXTRA_TARFILES = project/xscreensaver/res/drawable/thumbnail.png \
 
 echo_tarfiles:
-	@echo `find \
-		Makefile \
-		README \
-		*.[ch] *.pl \
-		project \
-		project/xscreensaver/res/drawable/*.png \
-		project/xscreensaver/res/values/settings.xml \
-		project/xscreensaver/res/values/strings.xml \
-	  \( \( -name '.??*' -o -name build -o -name gen \
-                -o -name libs -o -name obj -o -name '*~*' \) \
-	     -prune \) \
-	  -o \( -type f -o -type l \) -print \
-	| sed 's@^\./@@' \
-	| sort`
+	@FILES=`find . $(EXTRA_TARFILES) \( \(	\
+		   -name .DS_Store		\
+		-o -name '*~'			\
+		-o -name '*.keystore'		\
+		-o -name '*_dream.xml'		\
+		-o -name '*_settings.xml'	\
+		-o -name AndroidManifest.xml	\
+		-o -name strings.xml		\
+		-o -name settings.xml		\
+		-o -name attrs.xml		\
+		-o -name .gitignore		\
+		-o -name .gradle		\
+		-o -name drawable		\
+		-o -name build			\
+		-o -name gen			\
+		-o -name libs			\
+		-o -name obj			\
+		\) -prune \)			\
+		-o \( \( -type f -o -type l \)	\
+		      -print \)			\
+		| sed 's@^\./@@' 		\
+		| sort` ;			\
+	echo $$FILES
 
-apk: apk_raw_debug
+debug::
+	$(GRADLE) assembleDebug
+release::
+	export APP_ABI=all ; \
+	$(GRADLE) assembleRelease
 
-apk_raw_debug:
-		cd $(TARGET); ./gradlew assembleDebug
 
-gradle_clean:
-		-cd $(TARGET); ./gradlew clean
+KEYSTORE = xscreensaver.keystore
+$(KEYSTORE):
+	keytool -genkey -v -keystore $@ \
+	-alias xscreensaver -keyalg RSA -keysize 2048 -validity 10000
 
+APK_DIR       = project/xscreensaver/build/outputs/apk/
+APK_UNSIGNED  = $(APK_DIR)/xscreensaver-release-unsigned.apk
+APK_UNALIGNED = $(APK_DIR)/xscreensaver-release-unaligned.apk
+APK_SIGNED    = $(APK_DIR)/xscreensaver-release.apk
+
+  TOOLDIR = $(shell echo $$HOME/Library/Android/sdk/build-tools/* | tail -1)
+ ZIPALIGN = $(TOOLDIR)/zipalign
+JARSIGNER = jarsigner
+
+sign_release::
+	cp -p $(APK_UNSIGNED) $(APK_UNALIGNED)
+	$(JARSIGNER) -verbose -sigalg SHA1withRSA -digestalg SHA1 \
+		     -keystore $(KEYSTORE) $(APK_UNALIGNED) xscreensaver
+	rm -f $(APK_SIGNED)
+	$(ZIPALIGN) -v 4 $(APK_UNALIGNED) $(APK_SIGNED)
+	rm -f $(APK_UNALIGNED)
+	$(JARSIGNER) -verify -verbose -certs $(APK_SIGNED)
+	@ls -lF $(APK_SIGNED)
+
+apk:: release
+	@\
+  VERS=`sed -n 's/[^0-9]*\([0-9]\.[0-9][^. ]*\).*/\1/p' ../utils/version.h` ; \
+  HEAD="xscreensaver-$$VERS" ;						      \
+  if [ ! -s $(APK_SIGNED) -o $(APK_UNSIGNED) -nt $(APK_SIGNED) ]; then	\
+    $(MAKE) sign_release ;						\
+  fi ;									\
+  set -x ;								\
+  cp -p $(APK_SIGNED) ../archive/$$HEAD.apk
+
+
+## #### Pare it down for faster debugging...
+#export APP_ABI = armeabi-v7a
+#export APP_ABI = x86
+#
+#export ANDROID_HACKS=		\
+#	$(ANDROID_BASE_HACKS)	\
+#  bsod				\
+#  apollonian			\
+#  engine			\
+#  dnalogo			\
+#  twang			\
+#  memscroller			\
